# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=25)),
                ('questions', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tag'),
        ),
    ]
