# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160305_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note_Title', max_length=20),
        ),
    ]
